### ISSUE TITLE
RubyDNS 2.0.0-rc1 available, can you please test.

### ISSUE THREAD

**Issue by ioquatix** [cookpad/murakumo#3]
We are preparing for 1.0.0 release of RubyDNS. Changes are mostly performance and bug fixing, tidy up code base.

https://github.com/ioquatix/rubydns/issues/28

If possible can you please test with latest 0.8.x and report back. We aim to do 1.0.0 release of RubyDNS by the end of this month. Thanks for your help!

**Comment by ioquatix** [comment]
Bump :)

**Comment by ioquatix** [comment]
RubyDNS 2.0.0 is a big improvement to stability, if you have time to try it out and report any issues that would be great.

**Comment by sorah** [comment]
Thanks, but as my understanding, this project is no longer maintained. Sorry for being unresponsive on this issue for a while.

cc @winebarrel

**Comment by ioquatix** [comment]
That's fine, I thought as much. I just wanted to touch base again. I thought this was a cool project. I also like cookpad :)
